### PR TITLE
Add initial typings for resin-cli-form

### PR DESCRIPTION
**Pull request by thgreasi**
Change-type: patch
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

---
##### Contributor checklist

- [ ] Introduces security considerations
- [ ] Affects the development, build or deployment processes of the component

### CODE REVIEW

**Comment by pdcastro** [comment]
@thgreasi, I'm not sure of the background for this PR, but if could wait a couple of days, v11 will be merged to master and will require some changes to this PR. For example, `typings/resin-cli-form.d.ts` will probably need to become `typings/resin-cli-form/index.d.ts` because of the `ts-node` version bump. v11 also bumps typescript, which may or may not also affect some of the type changes.

**Comment by thgreasi** [comment]
If fine waiting for v11 @pdcastro :+1: 
A bit more context, this PR splits some of the chore work out of the [balena device os-update PR](https://github.com/balena-io/balena-cli/pull/1143), in order to make that PR easier to review.

**Comment by pdcastro** [comment]
`v11` is out, this PR can be rebased and updated. Thanks for waiting @thgreasi ! 👍

**Comment by thgreasi** [comment]
Will do so today @pdcastro . Thanks for the heads-up :+1:

**Pull request merged**
