### PR TITLE
Update balena-multibuild to 5.1.0

### PR DESCRIPTION
**Pull request by robertgzr**
Depends-on: https://github.com/balena-io-modules/balena-multibuild/pull/93
Change-type: patch
Signed-off-by: Robert Günzler <robertg@balena.io>

### CODE REVIEW

**Comment by robertgzr** [comment]
@pdcastro will fix the change types and 100% the builder pr should be merged and deployed before this work here

**Comment by vpetersson** [comment]
Will this also extend the `depends_on`/`condition` with `service_healthy` as well?

**Comment by robertgzr** [comment]
@vpetersson yes that's also contained here

**Comment by dfunckt** [comment]
@robertgzr this is not correct.

@vpetersson no, support for `service_healthy` is quite involved and is not added with this PR.

**Comment by karaxuna** [comment]
Tested `balena-cli@12.51.2-rgz-compose24-8c5f8db3f5cf8f8f3fc9d805a6d4baef1ff7c9aa` against staging.
All three services in my docker-compose.yml target different build stages in same dockerfile, but during build all three services build whole dockerfile from scratch and all three target the latest stage only (I see logs of third service in all containers).

**Comment by robertgzr** [comment]
@dfunckt @vpetersson upps, should have double-checked :eyes: 

In any case https://github.com/balena-io/docs/pull/2092/files#diff-6f555b8df872d999f8a8181b8ace6a5f528ea2a9c40700b3da23d5836f4458b5R31 reflects what is supported

**Comment by robertgzr** [comment]
@pdcastro can you give this another look?

**Comment by robertgzr** [comment]
I have tested this with the latest supervisor (to ensure livepush works [1])

<details>
<summary>[1] live push logs</summary

```
⋮ ~/devel/balena/_tmp/multistage_test ⬢ ❯ ~/devel/balena/balena-cli/bin/balena push 127.0.0.1
[Info]    Starting build on device 127.0.0.1
[Build]   [efg] Step 1/10 : FROM balenalib/amd64-alpine:run AS base
[Build]   [efg]  ---> 4d9e1007a224
[Build]   [efg] Step 2/10 : RUN touch /base
[Build]   [abc] Step 1/7 : FROM balenalib/amd64-alpine:run AS base
[Build]   [abc]  ---> 4d9e1007a224
[Build]   [abc] Step 2/7 : RUN touch /base
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> 7983f80f6d2b
[Build]   [efg] Step 3/10 : FROM base AS stage-0
[Build]   [efg]  ---> 7983f80f6d2b
[Build]   [efg] Step 4/10 : RUN touch /stage-0
[Build]   [abc]  ---> Using cache
[Build]   [abc]  ---> 7983f80f6d2b
[Build]   [abc] Step 3/7 : FROM base AS stage-0
[Build]   [abc]  ---> 7983f80f6d2b
[Build]   [abc] Step 4/7 : RUN touch /stage-0
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> e712f8619ad6
[Build]   [efg] Step 5/10 : CMD balena-idle --message abc
[Build]   [abc]  ---> Using cache
[Build]   [abc]  ---> e712f8619ad6
[Build]   [abc] Step 5/7 : CMD balena-idle --message abc
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> 763e849e2742
[Build]   [efg] Step 6/10 : FROM base AS stage-1
[Build]   [efg]  ---> 7983f80f6d2b
[Build]   [efg] Step 7/10 : RUN touch /stage-1
[Build]   [abc]  ---> Using cache
[Build]   [abc]  ---> 763e849e2742
[Build]   [abc] Step 6/7 : LABEL io.resin.local.image=1
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> 445f443c839d
[Build]   [efg] Step 8/10 : CMD balena-idle --message efg
[Build]   [abc]  ---> Using cache
[Build]   [abc]  ---> d1d6682a2c12
[Build]   [abc] Step 7/7 : LABEL io.resin.local.service=abc
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> e40c0d449fe2
[Build]   [efg] Step 9/10 : LABEL io.resin.local.image=1
[Build]   [abc]  ---> Using cache
[Build]   [abc]  ---> 75167865aabe
[Build]   [abc] Successfully built 75167865aabe
[Build]   [abc] Successfully tagged local_abc:latest
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> 26832c9c696f
[Build]   [efg] Step 10/10 : LABEL io.resin.local.service=efg
[Build]   [efg]  ---> Using cache
[Build]   [efg]  ---> 24621330ca48
[Build]   [efg] Successfully built 24621330ca48
[Build]   [efg] Successfully tagged local_efg:latest

[Info]    Streaming device logs...
[Live]    Watching for file changes...
[Live]    Waiting for device state to settle...
```

</details>


and the builder release with this is ready (just not deployed yet)

**Comment by karaxuna** [comment]
@robertgzr livepush does not work for me :( Can you try this branch? https://github.com/product-os/jellyfish/pull/7413

**Comment by pdcastro** [comment]
> @pdcastro can you give this another look?

@robertgzr, it looks like a couple of my previous comments have not been fully addressed yet:

> Can we reword _"Partially support long form of depends_on"_ to clarify what exactly is newly supported, "in 50 characters"? :-) cc: @dfunckt  I am assuming this is the only (really?) relevant new feature of "Update balena-compose-parse to 3.0.0" from CLI users' point of view, other than what we are already claiming for the multibuild commit (extra_hosts, shm_size, target, cachefrom) and short of claiming support for docker-compose v2.4 which could be misleading (is it not?) as explained above.

Looking at your docs PR balena-io/docs/pull/2092 (good job!), how about the following, assuming that it is correct:

`Changelog-entry: push/build/deploy: Support 'condition: service_started' in 'depends_on' service configuration in docker-compose.yml`

And also:

> And let's change the commits (both, I think) to have `Change-type: minor`, as I understand that both deliver new features from end users' point of view (something they can do after updating the CLI, that they could not do before).

>> The commits still have `Change-type: patch`, but I think they should be `minor`.

**Comment by robertgzr** [comment]
@pdcastro rebased and updated both of the commits. the builder change is live in prod now too :)

**Comment by pdcastro** [comment]
> @pdcastro rebased and updated both of the commits. the builder change is live in prod now too :)

Neat. 👍  The following comment from @karaxuna, is it something caused by this PR that is still pending resolution?

> https://github.com/balena-io/balena-cli/pull/2358#issuecomment-977639150
> @robertgzr livepush does not work for me :( Can you try this branch? product-os/jellyfish#7413

**Comment by pdcastro** [comment]
> The following comment from @karaxuna, is it something caused by this PR that is still pending resolution?
>> https://github.com/balena-io/balena-cli/pull/2358#issuecomment-977639150
>> @robertgzr livepush does not work for me :( Can you try this branch? product-os/jellyfish#7413

That question was discussed in [a Flowdock thread](https://www.flowdock.com/app/rulemotion/p-cyclops/threads/HRXLZkn0KQkRDhza7l53Qy4mEyt) (restricted access). In that thread, @karaxuna explained that that issue is no longer an issue:

> @robertgzr, it was due to image and build properties not working together, which was fixed by Lucian.

But in the process of investigating it, it sounds like @robertgzr found another issue:

> I feel like this should go to a product/arch call... we would either need to put a disclaimer that livepush is incompatible with `build.target` _or_ make it work _or_ deprecate the livepush directives in favour of something else

This sounds relevant to this PR because one of the commits in the PR states:

> Changelog-entry: push/build/deploy: Support new docker-compose.yml build parameters: extra_hosts, shm_size, target, cache_from

So we'd be claiming that `balena push` supports `build.target` but `balena push <ip-addr>` (a.k.a. livepush) _"is incompatible with `build.target`"._

It sounds like this needs to be clarified before this PR is merged. Discussion continuing in the FD thread (or here).

**Comment by dfunckt** [comment]
@robertgzr @pdcastro any way we can push this forward?

Is the blocker

> we'd be claiming that balena push supports build.target but balena push <ip-addr> (a.k.a. livepush) "is incompatible with build.target"

?

**Comment by robertgzr** [comment]
@dfunckt the problem is our custom livepush directives and maybe the fundamental assumptions made by livepush. At least the former don't consider that a build might terminate at an intermediate build stage, which is possible with `build.target` in compose 2.4

**Comment by dfunckt** [comment]
Superseded by #2476

**Pull request closed without merging**
