### PR TITLE
Update oclif, improve help command

### PR DESCRIPTION
**Pull request by myarmolinsky**
Update oclif, improve help command

BEFORE: 69 vulnerabilities (1 low, 25 moderate, 31 high, 12 critical)
AFTER: 52 vulnerabilities (1 low, 23 moderate, 21 high, 7 critical)

Change-type: minor

---
Please check the CONTRIBUTING.md file for relevant information and some
guidance. Keep in mind that the CLI is a cross-platform application that runs
on Windows, macOS and Linux. Tests will be automatically run by balena CI on
all three operating systems, but this will only help if you have added test
code that exercises the modified or added feature code.

Note that each commit message (currently only the first line) will be
automatically copied to the CHANGELOG.md file, so try writing it in a way
that describes the feature or fix for CLI users.

If there isn't a linked issue or if the linked issue doesn't quite match the
PR, please add a PR description to explain its purpose or the features that it
implements. Adding PR comments to blocks of code that aren't self explanatory
usually helps with the review process.

If the PR introduces security considerations or affects the development, build
or release process, please be sure to highlight this in the PR description.

Thank you very much for your contribution!

### CODE REVIEW

**Comment by otaviojacobi** [comment]
Tests disabled for testing publish action DO NOT MERGE

**Comment by otaviojacobi** [comment]
Standalone mac works but build for windows did not work as node loader can't find the built binary.... will continue next friday

**Comment by otaviojacobi** [comment]
Windows .exe build works. Need to test standalone

**Comment by myarmolinsky** [comment]
LGTM

**Pull request merged**
