### PR TITLE
build linux/arm packages 

### PR DESCRIPTION
**Pull request by ab77**
draft/test: https://github.com/product-os/self-hosted-runners/pull/41

### CODE REVIEW

**Comment by klutchell** [comment]
A more static link for binaries to test: https://github.com/balena-io/balena-cli/releases/tag/ab77%2Foperational

**Comment by klutchell** [comment]
@ab77 the balenaOS cloud suite passed for me locally on arm64, and it uses a number of CLI features like os configure, preload, push, etc. So that's promising.

**Comment by ab77** [comment]
> @ab77 the balenaOS cloud suite passed for me locally on arm64, and it uses a number of CLI features like os configure, preload, push, etc. So that's promising.

let me know when you are confident, maybe also @aethernet can do some quick preloading tests.

**Comment by klutchell** [comment]
My primary workstation is MacOS so I can't test in my day-to-day. The best I can do is bump some components that use the CLI in Docker.

**Comment by ab77** [comment]
> My primary workstation is MacOS so I can't test in my day-to-day. The best I can do is bump some components that use the CLI in Docker.

@fisehara @joehounsham please ping this PR when customer(s) have tested..

**Comment by ab77** [comment]
lgtm

**Pull request merged**
