### PR TITLE
Update packages in response to colors package issues

### PR DESCRIPTION
**Pull request by srlowe**
Change-type: patch
Signed-off-by: Scott Lowe <scott@balena.io>

### CODE REVIEW

**Comment by srlowe** [comment]
@balena-ci I self-certify!

**Comment by srlowe** [comment]
@balena-ci retest

**Comment by srlowe** [comment]
@balena-ci retest

**Comment by srlowe** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Pull request merged**
