### PR TITLE
Use Actuated runners for Linux test and publish

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch

Resolves: #   
Change-type: major|minor|patch   
Depends-on: <url>   
See: <url>   

---
Please check the CONTRIBUTING.md file for relevant information and some
guidance. Keep in mind that the CLI is a cross-platform application that runs
on Windows, macOS and Linux. Tests will be automatically run by balena CI on
all three operating systems, but this will only help if you have added test
code that exercises the modified or added feature code.

Note that each commit message (currently only the first line) will be
automatically copied to the CHANGELOG.md file, so try writing it in a way
that describes the feature or fix for CLI users.

If there isn't a linked issue or if the linked issue doesn't quite match the
PR, please add a PR description to explain its purpose or the features that it
implements. Adding PR comments to blocks of code that aren't self explanatory
usually helps with the review process.

If the PR introduces security considerations or affects the development, build
or release process, please be sure to highlight this in the PR description.

Thank you very much for your contribution!

### CODE REVIEW

**Comment by klutchell** [comment]
@otaviojacobi @thgreasi this is exactly what I did in my second commit, what am I missing?
```plain
** npm-shrinkwrap.json was not deduplicated or not fully committed - FAIL **
** This can usually be fixed with: **
** git checkout master -- npm-shrinkwrap.json **
** rm -rf node_modules **
** npm install && npm dedupe && npm install **
Error: "test-shrinkwrap": /home/runner/work/balena-cli/balena-cli/automation/test-lock-deduplicated.sh failed with exit code 1:
"/home/runner/work/balena-cli/balena-cli/automation/test-lock-deduplicated.sh" []
```

**Comment by klutchell** [comment]
So how can I tell which npm version I need to use?

**Comment by otaviojacobi** [comment]
> So how can I tell which npm version I need to use?

Usually I will check which one is flowzone using: 
```
Environment details
  node: v20.12.2
  npm: 10.5.0
```

I suppose npm 10.5.0

**Comment by klutchell** [comment]
Have we considered adding `test:shrinkwrap` to husky pre-commit hooks? Or even the entire dedupe command but that may be overkill.

**Comment by otaviojacobi** [comment]
> Have we considered adding `test:shrinkwrap` to husky pre-commit hooks? Or even the entire dedupe command but that may be overkill.

The issue is exactly that `test:shrinkwrap` underneath the hook needs to run `npm i && npm dd && npm i` which is very slow for a commit hook (maybe 5 minutes)?

**Comment by klutchell** [comment]
> which is very slow for a commit hook

yeah, I came to that conclusion

**Comment by otaviojacobi** [comment]
If I ran on your commit previous to Thodoris commit I still get a difference on sha calculation. Idk how exactly

**Comment by klutchell** [comment]
> @klutchell
> 
> > Run tar --exclude-vcs -acf /home/runner/actions-runner/_work/_temp/custom.tgz .
> > tar --exclude-vcs -acf /home/runner/actions-runner/_work/_temp/custom.tgz .
> > Error: pwsh: command not found

I saw that, I'm asking the Actuated team to install pwsh.

**Review by thgreasi — APPROVED** [review]

**Review by otaviojacobi — APPROVED** [review]

**Pull request merged**
