### PR TITLE
meta: Americanize all spellings

### PR DESCRIPTION
**Pull request by xginn8**
Connects-to: https://github.com/balena-io/docs/issues/1300
Change-type: patch
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

Btw, this build issue is caused by unavailable workers in the Seattle office:
https://www.flowdock.com/app/rulemotion/o-seattle/threads/a45SZFJvu54w2FuavfCidYXc22l

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by hedss** [comment]
@balena-ci retest

**Comment by xginn8** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
> **ResinCI/node-cli/node-cli** _Expected — Waiting for status to be reported_

This is caused by unavailable balena CI machines or networking nodes in the Seattle office:
* https://www.flowdock.com/app/rulemotion/o-seattle/threads/a45SZFJvu54w2FuavfCidYXc22l
* https://ci.balena-dev.com/teams/main/pipelines/github-events-resin/jobs/node-cli/builds/347
```
no workers satisfying: platform 'darwin', tag 'onprem'
no workers satisfying: platform 'windows', tag 'onprem'
```
Already for a week. :-(

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by xginn8** [comment]
@balena-ci retest

**Pull request merged**
