### PR TITLE
ssh: fix incorrect service name parsing in local mode

### PR DESCRIPTION
**Pull request by tmigone**
Silly bug that was bothering me for some time now :P

Resolves: #2252
Change-type: patch
Signed-off-by: Tomás Migone <tomas@balena.io>

### CODE REVIEW

**Review by pdcastro — APPROVED** [review]
👍

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@pdcastro does `ResinCI/node-cli/node-cli` usually take long? Earlier today it was still pending after 15 hours, I've retested half an hour ago.

**Comment by pdcastro** [comment]
> @pdcastro does `ResinCI/node-cli/node-cli` usually take long? Earlier today it was still pending after 15 hours, I've retested half an hour ago.

It should take well less than half an hour. The error is:

```
> test-windows-x64
no workers satisfying: platform 'windows', tag 'balena:onprem'
```
https://ci.balena-dev.com/teams/main/pipelines/github-events-balena-io/jobs/node-cli/builds/515

The CI Windows worker(s) is(are) dead, a matter of reaching to devops / balenaci teams...

**Pull request merged**
