### PR TITLE
Add caxa-based installer for Linux

### PR DESCRIPTION
**Pull request by pdcastro**
This PR is an attempt at how balena CI could be used to generate a caxa-based installer for Linux. See:

* Handover notes: https://docs.google.com/document/d/1NxYwQrmSakQvwf9v8hXhCzuJzoQOjKZWrWZOZM4edI4/edit?usp=sharing
* JF improvement: https://jel.ly.fish/product-improvement-provide-a-friendly-installer-for-the-balena-cli-on-linux-0a731e74-668a-445e-9c43-383ffcc44620
* Comparison GSheet: [https://docs.google.com/spreadsheets/d/1VboFnh0U74Nl0xwdesG6z3pnMfPPFcn19_NrD6SYxKQ/edit](https://docs.google.com/spreadsheets/d/1VboFnh0U74Nl0xwdesG6z3pnMfPPFcn19_NrD6SYxKQ/edit?usp=sharing)
* FD discussion: https://www.flowdock.com/app/rulemotion/i-cli/threads/lqsgv7orNqQAinI5hwKYDs66nLw
* FD discussion: https://www.flowdock.com/app/rulemotion/r-etcherprv/threads/BekPuhzGT1El9XkB8lpne33HwMQ

Change-type: minor

### CODE REVIEW

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by ab77** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci retest

**Pull request closed without merging**
