### PR TITLE
Improve installation docs regarding Docker Desktop version requirements

### PR DESCRIPTION
**Pull request by pdcastro**
Connects-to: #2228
Change-type: patch

### CODE REVIEW

**Comment by pdcastro** [comment]
@balena-ci retest

**Comment by pdcastro** [comment]
@balena-ci I self-certify!

**Comment by maggie0002** [comment]
Thanks for the info.

What is it about the Raspberry Pi 3 that means this won't work? I am trying a preload on Orange Pi Zero BalenaOS 2.60.1+rev1 and it appears to go through (at least appears too, I assume I would receive error messages rather than a corrupt build).

Should I be looking for Balena OS version numbers? 64bit vs 32 bit builds?

**Comment by pdcastro** [comment]
> What is it about the Raspberry Pi 3 that means this won't work?

@maggie0002, it is not exactly the balenaOS version, nor 64bit vs 32bit, nor a lack of capability of the device type (RPi 3 vs RPi 4). If you open a Host OS terminal on a device running balenaOS, with the RPi 3 you will see this `aufs` folder:
```
root@9a56d9b:~# ls -l /mnt/data/docker/aufs/
total 468
drwx------ 1071 root root 155648 Mar 26 16:28 diff
drwx------    2 root root 155648 Mar 26 16:28 layers
drwx------ 1071 root root 155648 Mar 26 16:28 mnt

root@9a56d9b:~# ls -l /mnt/data/docker/aufs/layers/
total 4068
-rw-r--r-- 1 root root 1495 Mar 14 00:08 00032c7a32c37bd238449d3de6ada51f6d363192f76b111dd10b1893e995f738
-rw-r--r-- 1 root root 1755 Mar 14 00:08 006f1e72b62e297a62658b8d61e8c077e7a1e4edcf374b76e05a769893c1fded
```

While with the RPi 4 you will see an `overlay2` folder instead:
```
root@b408a70:~# ls -l /mnt/data/docker/overlay2/
total 164
drwx------ 4 root root 4096 Mar 16 13:37 05eab514d7c4be8fb43f9d8149b9ae3178577a26397772bb854f1e780d763d6e
drwx------ 4 root root 4096 Mar 16 13:38 0a0d69cabf943d97016b5c1ce6b7a43acd8e66f9ca8216204b78f68c430fdaad
...
```

The contents of these folders are the storage filesystem of application containers and images listed with `balena-engine images` (equivalent of `docker images`), in either the [aufs](https://docs.docker.com/storage/storagedriver/aufs-driver/) or [overlay2](https://docs.docker.com/storage/storagedriver/overlayfs-driver/) formats (which of course are incompatible).

I understand that the same version of balenaOS will include either the `aufs` folder or the `overlay2` folder, depending on the device type. I believe this is currently a "hardcoded setting" per device type. A device image downloaded from the dashboard, even before preloading, will already contain one folder or the other. The `balena preload` command will then populate one of those folders (inside the balenaOS image) with an application release.

Also, if I recall correctly, balenaOS host OS updates were designed so that the [rootA / rootB partitions](https://www.balena.io/docs/reference/OS/overview/2.x/#image-partition-layout) are also structured as Docker / balenaEngine images in one of those formats. References:

* https://github.com/balena-os/balenahup/issues/301  
_"Assume you have a device that uses AUFS for the container filesystem, and are upgrading to a version of the OS that uses overlay2. Currently, `balenahup` will happily apply this update and reboot; however, the device will panic at boot time because the containers have not been migrated to the overlay2 filesystem."_
* https://github.com/balena-os/balena-engine/issues/205

So I think the difficulty of converting from aufs to overlay2 is managing the data format migration on existing devices, as the `/mnt/data/docker` partition persists across Host OS upgrades, and the `rootA` / `rootB` partitions as well. The balenaOS team has been working on a [overlay2 migration utility](https://github.com/balena-os/balena-engine/pull/168) which I believe is almost complete and will be included in balenaOS 3.0, which is planned to be released in the next few months. I am not an "authoritative source" for this information but it is what I am aware of at the moment.

**Comment by maggie0002** [comment]
Thanks @pdcastro. I have taken enough from that to have concluded that doing all preloads on a Linux VM for all devices is going to be the way to go, just to avoid the uncertainty until OS 3.0.

**Comment by pdcastro** [comment]
> I am trying a preload on Orange Pi Zero BalenaOS 2.60.1+rev1 and it appears to go through

@maggie0002, I have now tested and confirmed that the Orange Pi Zero, like the RPi 4, already uses overlay2 instead of aufs, so you can use `balena preload` with the latest version of Docker Desktop on macOS or Windows, and there is no need to use a Linux VM (for the Orange Pi Zero).

> it appears to go through (at least appears too, I assume I would receive error messages rather than a corrupt build).

`balena preload` would fail and produce an error message: `error initializing graphdriver: driver not supported` if the device type used AUFS and Docker didn't support AUFS. More details on issue #1099.

**Comment by maggie0002** [comment]
Thanks again @pdcastro.

OPI Zero happened to just be the one I was working on, I intend to be building a lot more images too. Using the Linux VM seemed like an easier way to go than checking and tracking them all. It was something on my to do list for a while anyway, and overall I think this improves my workflow.

If interested, I ended up using a GitHub Action: https://github.com/LearnersBlock/learners-block/blob/develop/.github/workflows/deploy-release.yml

**Pull request merged**
