### PR TITLE
Use all available on-device images during local push

### PR DESCRIPTION
**Pull request by CameronDiver**
Change-type: patch
Signed-off-by: Cameron Diver <cameron@balena.io>

---
##### Contributor checklist

- [ ] Introduces security considerations
- [ ] Affects the development, build or deployment processes of the component

### CODE REVIEW

**Comment by shaunmulligan** [comment]
@CameronDiver and @pdcastro why didn't we merge this one? seems useful

**Comment by pdcastro** [comment]
> @CameronDiver and @pdcastro why didn't we merge this one? seems useful

I am not aware of a reason. Maybe just forgotten?

**Comment by shaunmulligan** [comment]
cool, yeah that would be my guess. Lets get it out there, otherwise its just work we have done but aren't getting the benefit from :)

**Comment by hedss** [comment]
@CameronDiver Pokey pokey ;-)

**Pull request merged**
