### PR TITLE
Adding information about dependency installation

### PR DESCRIPTION
**Pull request by pcgeek86**
Added documentation about the dependencies required to build balena-cli

Moved from https://github.com/balena-io/docs/pull/995

Resolves: # 
See: <url> 
Depends-on: <url> 
Change-type: major|minor|patch 

---
##### Contributor checklist

- [ ] Introduces security considerations
- [ ] Affects the development, build or deployment processes of the component

### CODE REVIEW

**Comment by pcgeek86** [comment]
@shaunmulligan Thanks, how do we get these automated checks to pass? Are there any issues we need to resolve elsewhere?

**Comment by shaunmulligan** [comment]
@pcgeek86 I believe its failing because of the commit format, you need it to match something like this: https://github.com/balena-io/balena-cli/commit/0f302d30eccfaa9ea72f1c114c615794b3ba26dc with:
```
fix: blabla 

Change-type: minor
Signed-off-by: Paulo Castro <paulo@balena.io>

**Comment by pcgeek86** [comment]
@shaunmulligan I amended the commit message using the template you provided. Let me know if this looks okay.

**Comment by lurch** [comment]
I noticed that the Travis builds for this PR were failing. Out of curiosity (and boredom :wink: ) I decided to dig into it, and _eventually_ figured out that the `doc/cli.markdown` that this PR modifies is actually an output file, and I think the file you **should** have edited is `capitanodoc.ts` ? (See https://github.com/balena-io/balena-cli/blob/master/package.json#L38 )

Suggestion: Perhaps capitanodoc (whatever that is) could automatically insert a comment into the markdown files it creates, warning that they shouldn't be edited directly? (i.e. similar to https://github.com/balena-io-modules/drivelist/pull/164#pullrequestreview-37358006 and https://raw.githubusercontent.com/balena-io-modules/drivelist/master/README.md )

**Comment by pcgeek86** [comment]
@lurch Thanks for digging into this. I'm learning about this repo myself. Based on a little more research:

- [capitano](https://www.npmjs.com/package/capitano) is an npm dependency (package.json) [for this project](https://github.com/balena-io/balena-cli/blob/master/package.json), which offers an interface to build command line tools (similar to commander.js)
- It would appear that [capitanodoc.ts](https://github.com/balena-io/balena-cli/blob/master/capitanodoc.ts) is a file containing documentation for the Balena CLI tool
- This file is used in the `npm run build:doc` command that you referenced in `package.json`

Looks like you are spot on ... I need to go back and update `capitanodoc.ts` instead. Cheers for the help.

**Pull request merged**
