### PR TITLE
Drop unused awaitDevice utility function

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Review by pdcastro — APPROVED** [review]
Build failing for Windows because the code signing certificate expired. I understand that Apo has already ordered a new certificate and is waiting to received the files, at which point he will send them securely to Anton for deployment in Vault. More details in the following FD thread: https://www.flowdock.com/app/rulemotion/r-operations/threads/fJt9oQgD0HUHmwPcrb_U94nN__M

If this PR was urgent, we could change the CI to skip the graphical installer for Windows when producing a release. But it is not urgent and I assume it is "a matter of 24 hours" until the new certificate is in place. 🤞

**Comment by LucianBuzzo** [comment]
Cool, thanks for the headsup @pdcastro

**Comment by pdcastro** [comment]
@balena-ci rebase

**Comment by pdcastro** [comment]
@balena-ci retest

**Pull request merged**
