### PR TITLE
Tests part 3: Convert tests to Typescript

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Depends-on: https://github.com/balena-io/balena-cli/pull/1386

---
##### Contributor checklist

- [ ] Introduces security considerations
- [x] Affects the development, build or deployment processes of the component

### CODE REVIEW

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Comment by LucianBuzzo** [comment]
@balena-ci retest

**Pull request merged**
